//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ranch_Max
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedPreparing
    {
        public int Id { get; set; }
        public int Formula_Id { get; set; }
        public int StockItem_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Rate { get; set; }
    
        public virtual FeedFormula FeedFormula { get; set; }
        public virtual StockItem StockItem { get; set; }
    }
}
