//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ranch_Max
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medication
    {
        public int Medication_Id { get; set; }
        public int StockItem_Id { get; set; }
        public string User_Id { get; set; }
        public int Animal_Id { get; set; }
        public int Quantity { get; set; }
        public string Unit { get; set; }
        public string Method { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual StockItem StockItem { get; set; }
    }
}
