//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ranch_Max
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilkBuyer
    {
        public int MilkBuyer_Id { get; set; }
        public int Buyer_Id { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<int> Rate { get; set; }
    
        public virtual Buyer Buyer { get; set; }
    }
}
