//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ranch_Max
{
    using System;
    using System.Collections.Generic;
    
    public partial class Milking
    {
        public int Milking_Id { get; set; }
        public Nullable<int> Animal_Id { get; set; }
        public string User_Id { get; set; }
        public Nullable<double> Amount_Ltr { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Slot { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
