//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ranch_Max
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdd
    {
        public int StockAdd_Id { get; set; }
        public int StockItem_Id { get; set; }
        public string User_Id { get; set; }
        public Nullable<int> TotalBags_Packs { get; set; }
        public Nullable<int> BagSize_PackSize { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual StockItem StockItem { get; set; }
    }
}
