//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ranch_Max
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockRemaining
    {
        public int StockRemaining_Id { get; set; }
        public int StockItem_Id { get; set; }
        public Nullable<int> Quantity_In { get; set; }
        public Nullable<int> Quantity_Out { get; set; }
        public Nullable<int> Remaining { get; set; }
    }
}
